# Generated by Django 3.2.24 on 2024-03-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='speacial_price',
        ),
        migrations.AddField(
            model_name='product',
            name='special_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
