# Generated by Django 3.2.24 on 2024-03-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20240330_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.CharField(default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='special_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True),
        ),
    ]
