# Generated by Django 3.2.24 on 2024-04-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='special_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
