# Generated by Django 3.2.24 on 2024-04-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='all_specials',
            field=models.BooleanField(default=False),
        ),
    ]
